server:
  port: ${PORT:2333}
  address: 0.0.0.0

lavalink:
  server:
    password: "tejvfr"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      lowpass: true
